# ====================================================
# Makefile build 'Pai project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/pair -g

val:
	valgrind ../bin/pai