# ====================================================
# Makefile build 'Queue project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../../../Array/include/ -o bin/queueArray -g

val:
	valgrind ../bin/queueArray