# ====================================================
# Makefile build 'Array project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/array -g

val:
	valgrind ../bin/array