# ====================================================
# Makefile build 'Stack project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/stackArray -g

val:
	valgrind ../bin/stackArray