# ====================================================
# Makefile build 'Hashmap project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../../../Linked_List/include/ -o bin/hashmap -g

val:
	valgrind ../bin/hashmap