# ====================================================
# Makefile build 'Matrix project' using Make
# ====================================================
all:
	g++ -Wall -std=c++17 src/drive.cpp -I include/ -I ../Array/include/ -o bin/matrix -g

val:
	valgrind ../bin/matrix