# ====================================================
# Makefile build 'Generic tree project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/genericTree -g

val:
	valgrind ../bin/genericTree