# ====================================================
# Makefile build 'Queue project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../../../Linked_List/include/ -o bin/queueLL -g

val:
	valgrind ../bin/queueLL