# ====================================================
# Makefile build 'Linked List project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/linkedList -g

val:
	valgrind ../bin/linkedList